main: fr.birdo.firemeloncore.FireMelonCore

name: FireMelonCore

description: Plugin pour le SMP FireMelon.

author: Birdo

version: 1.0

api-version: 1.16

commands:
  fm:
    description: Plugin commands
  recipes:
    description: List of plugin recipes